# server:
#     port: 9999
org:
  techbd:
    aws:
      region: ${ORG_TECHBD_SERVICE_AWS_REGION:us-east-1}
      secret-name: ${ORG_TECHBD_SERVICE_SECRET_NAME:default-secret}
      sqs:
        base-url: ${ORG_TECHBD_SERVICE_SQS_BASE_URL:https://sqs.us-east-1.amazonaws.com}
        fifo-queue-url: ${AWS_SQS_QUEUE_NAME:default-fifo-url}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME:default-bucket}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:sandbox}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always

togglz: 
  enabled: true 
  features: 
    DEBUG_LOG_REQUEST_HEADERS: 
      enabled: true  